# Generated by Django 3.2.7 on 2021-09-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('nationality', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.IntegerField()),
                ('qualification', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('pan_number', models.CharField(max_length=50)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
