# Generated by Django 3.2.7 on 2021-09-19 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_project', '0002_reponseinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponseinfo',
            name='reason',
        ),
    ]
