# Generated by Django 3.2.7 on 2021-09-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_project', '0003_remove_reponseinfo_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponseinfo',
            name='request_id',
            field=models.IntegerField(default=None),
        ),
    ]
