# Generated by Django 3.2.7 on 2021-09-20 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_project', '0004_alter_reponseinfo_request_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReponseInfo',
            new_name='ResponseInfo',
        ),
        migrations.AlterModelTable(
            name='requestinfo',
            table='RequestInfo',
        ),
        migrations.AlterModelTable(
            name='responseinfo',
            table='ResponseInfo',
        ),
    ]
